[project]
name = "text-mining-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=7.1.0",
    "pip>=25.3",
    "scispacy>=0.6.2",
    "spacy>=3.8.11",
]
